FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln .
COPY FastTech.Kitchen.Api/*.csproj ./FastTech.Kitchen.Api/
COPY FastTech.Kitchen.Application/*.csproj ./FastTech.Kitchen.Application/
COPY FastTech.Kitchen.Domain/*.csproj ./FastTech.Kitchen.Domain/
COPY FastTech.Kitchen.Infrastructure/*.csproj ./FastTech.Kitchen.Infrastructure/
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "FastTech.Kitchen.Api.dll"]
