version: '3.9'

services:
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - fasttech-network

  catalogo-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fasttech_catalogo
    volumes:
      - catalogo_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
    networks:
      - fasttech-network

  catalogo-migrations:
    build:
      context: ./catalogo-api
      dockerfile: FastTech.Catalogo/Dockerfile-migration
    depends_on:
      catalogo-mysql:
        condition: service_healthy
    networks:
      - fasttech-network

  catalogo-api:
    build:
      context: ./catalogo-api
      dockerfile: FastTech.Catalogo/Dockerfile
    image: fasttech-catalogo-api
    ports:
      - "8081:8080"
    depends_on:
      catalogo-mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTION_STRING: "Server=catalogo-mysql;Database=fasttech_catalogo;User=root;Password=123456;Port=3306;"
      RABBITMQ_HOST: rabbitmq
    restart: always
    networks:
      - fasttech-network

  auth-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fasttech_autenticacao
    volumes:
      - auth_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
    networks:
      - fasttech-network

  auth-migrations:
    build:
      context: ./autenticacao-api
      dockerfile: FastTech.Autenticacao/Dockerfile-migration
    depends_on:
      auth-mysql:
        condition: service_healthy
    networks:
      - fasttech-network

  auth-api:
    build:
      context: ./autenticacao-api
      dockerfile: FastTech.Autenticacao/Dockerfile
    image: fasttech-auth-api
    ports:
      - "8082:8080"
    depends_on:
      auth-mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTION_STRING: "Server=auth-mysql;Database=fasttech_autenticacao;User=root;Password=123456;Port=3306;"
      RABBITMQ_HOST: rabbitmq
    restart: always
    networks:
      - fasttech-network

  pedido-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fasttech_pedido
    volumes:
      - pedido_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
    networks:
      - fasttech-network

  pedido-migrations:
    build:
      context: ./pedido-api
      dockerfile: FastTech.Pedido/Dockerfile-migration
    depends_on:
      pedido-mysql:
        condition: service_healthy
    networks:
      - fasttech-network

  pedido-api:
    build:
      context: ./pedido-api
      dockerfile: FastTech.Pedido/Dockerfile
    image: fasttech-pedido-api
    ports:
      - "8083:8080"
    depends_on:
      pedido-mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTION_STRING: "Server=pedido-mysql;Database=fasttech_pedido;User=root;Password=123456;Port=3306;"
      RABBITMQ_HOST: rabbitmq
    restart: always
    networks:
      - fasttech-network

  kitchen-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fasttech_kitchen
    volumes:
      - kitchen_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
    networks:
      - fasttech-network

  kitchen-migrations:
    build:
      context: ./kitchen-api
      dockerfile: FastTech.Kitchen/Dockerfile-migration
    image: kitchen-migrations-image
    restart: "no"
    depends_on:
      kitchen-mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__Kitchen: "Server=kitchen-mysql;Database=fasttech_kitchen;User=root;Password=123456;Port=3306;"
    networks:
      - fasttech-network

  kitchen-api:
    build:
      context: ./kitchen-api
      dockerfile: FastTech.Kitchen/Dockerfile
    image: fasttech-kitchen-api
    ports:
      - "8084:8080"
    depends_on:
      kitchen-mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Kitchen: "Server=kitchen-mysql;Database=fasttech_kitchen;User=root;Password=123456;Port=3306;"
      RABBITMQ_HOST: rabbitmq
    restart: always
    networks:
      - fasttech-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fasttech-network

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - fasttech-network

volumes:
  catalogo_mysql_data:
  auth_mysql_data:
  pedido_mysql_data:
  kitchen_mysql_data:

networks:
  fasttech-network: