FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /src
COPY . .
WORKDIR "/src/FastTech.Catalogo/FastTech.Catalogo.Infrastructure"
RUN dotnet restore FastTech.Catalogo.Infrastructure.csproj \
 && dotnet tool install --global dotnet-ef \
 && dotnet ef database update \
      --project FastTech.Catalogo.Infrastructure.csproj \
      --startup-project ../FastTech.Catalogo.Api/FastTech.Catalogo.Api.csproj