FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /src
COPY . .
WORKDIR "/src/FastTech.Pedido/FastTech.Pedido.Infrastructure"
RUN dotnet restore FastTech.Pedido.Infrastructure.csproj \
 && dotnet tool install --global dotnet-ef \
 && dotnet ef database update \
      --project FastTech.Pedido.Infrastructure.csproj \
      --startup-project ../FastTech.Pedido.Api/FastTech.Pedido.Api.csproj