FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /src
COPY . .
WORKDIR "/src/FastTech.Autenticacao/FastTech.Autenticacao.Infrastructure"
RUN dotnet restore FastTech.Autenticacao.Infrastructure.csproj \
 && dotnet tool install --global dotnet-ef \
 && dotnet ef database update \
      --project FastTech.Autenticacao.Infrastructure.csproj \
      --startup-project ../FastTech.Autenticacao.Api/FastTech.Autenticacao.Api.csproj