name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore autenticacao-api/FastTech.Autenticacao/FastTech.Autenticacao.sln
        dotnet restore catalogo-api/FastTech.Catalogo/FastTech.Catalogo.sln
        dotnet restore pedido-api/FastTech.Pedido/FastTech.Pedido.sln
        dotnet restore kitchen-api/FastTech.Kitchen/FastTech.Kitchen.sln

    - name: Build
      run: |
        dotnet build --no-restore autenticacao-api/FastTech.Autenticacao/FastTech.Autenticacao.sln
        dotnet build --no-restore catalogo-api/FastTech.Catalogo/FastTech.Catalogo.sln
        dotnet build --no-restore pedido-api/FastTech.Pedido/FastTech.Pedido.sln
        dotnet build --no-restore kitchen-api/FastTech.Kitchen/FastTech.Kitchen.sln

    - name: Test
      run: |
        dotnet test --no-build --verbosity normal autenticacao-api/FastTech.Autenticacao/FastTech.Autenticacao.sln
        dotnet test --no-build --verbosity normal catalogo-api/FastTech.Catalogo/FastTech.Catalogo.sln
        dotnet test --no-build --verbosity normal pedido-api/FastTech.Pedido/FastTech.Pedido.sln
        # dotnet test --no-build --verbosity normal kitchen-api/FastTech.Kitchen/FastTech.Kitchen.sln # Adicionar quando os testes forem criados

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push autenticacao-api
      uses: docker/build-push-action@v3
      with:
        context: ./autenticacao-api/FastTech.Autenticacao
        file: ./autenticacao-api/FastTech.Autenticacao/dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fasttech-autenticacao-api:latest

    - name: Build and push catalogo-api
      uses: docker/build-push-action@v3
      with:
        context: ./catalogo-api/FastTech.Catalogo
        file: ./catalogo-api/FastTech.Catalogo/dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fasttech-catalogo-api:latest

    - name: Build and push pedido-api
      uses: docker/build-push-action@v3
      with:
        context: ./pedido-api/FastTech.Pedido
        file: ./pedido-api/FastTech.Pedido/FastTech.Pedido.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fasttech-pedido-api:latest

    - name: Build and push kitchen-api
      uses: docker/build-push-action@v3
      with:
        context: ./kitchen-api/FastTech.Kitchen
        file: ./kitchen-api/FastTech.Kitchen/dockerfile # Adicionar dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fasttech-kitchen-api:latest

    - name: Deploy to Kubernetes
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f iac/
